import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { headers } from "next/headers";
import { Providers } from "@/components/providers";

const fontSans = localFont({
  src: [
    {
      path: "../fonts/InterVariable.woff2",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "../fonts/InterVariable-Italic.woff2",
      weight: "100 900",
      style: "italic",
    },
  ],
  variable: "--font-inter",
});

const fontMono = localFont({
  src: [
    { path: "../fonts/geist-mono.woff2", weight: "100 900", style: "normal" },
  ],
  variable: "--font-geist-mono",
});

const appName = "Intent UI Starter Kit";

export const metadata: Metadata = {
  title: {
    default: appName,
    template: `%s | ${appName}`,
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const acceptLanguage = (await headers()).get("accept-language");
  const lang = acceptLanguage?.split(/[,;]/)[0] || "en-US";
  return (
    <html lang="en" suppressHydrationWarning data-scroll-behavior="smooth">
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        <Providers lang={lang}>{children}</Providers>
      </body>
    </html>
  );
}
