import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { RouterProvider } from "@/components/router-provider";
import { ThemeProvider } from "@/components/theme-provider";

const fontSans = localFont({
  src: [
    { path: "./InterVariable.woff2", weight: "100 900", style: "normal" },
    {
      path: "./InterVariable-Italic.woff2",
      weight: "100 900",
      style: "italic",
    },
  ],
  variable: "--font-inter",
});

const fontMono = localFont({
  src: [{ path: "./geist-mono.woff2", weight: "100 900", style: "normal" }],
  variable: "--font-geist-mono",
});

const appName = "Starter";

export const metadata: Metadata = {
  title: {
    default: appName,
    template: `%s | ${appName}`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        <RouterProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </RouterProvider>
      </body>
    </html>
  );
}
